#inherit_from: configs/pointcloud/onet_pretrained.yaml
inherit_from: configs/img/onet_pretrained.yaml

#data:
#  mesh_gt_root: /private/home/kalyanv/learning_vision3d/datasets/ShapeNetCore.v1

training:
  out_dir:  results_multi/demo
generation:
  opt_batch_size: 2008
  model_type: 'multi'

  opt_iters: 4000
  rnd_restart_num: 5
  sampling_type: 'random'  

  vis_n_outputs: 4
  generation_dir: generation
  refinement_step: 0
  simplify_nfaces: 5000
  generate_mesh: true
  generate_pointcloud: false

